### ISSUE TITLE
Error from GIF

### ISSUE THREAD

**Issue by Daniel-Ric** [Him188/MyMap#12]
[36m19:11:35[m [[m[34mINFO [m[m] Aktiviere MyMap v1.5

[36m19:11:36[m [[m[1;31mERROR[m[m] Throwing

java.lang.RuntimeException: java.lang.NullPointerException

at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [nukkit.jar:?]

at cn.nukkit.Server.enablePlugin(Server.java:733) [nukkit.jar:?]

at cn.nukkit.Server.enablePlugins(Server.java:722) [nukkit.jar:?]

at cn.nukkit.Server.<init>(Server.java:558) [nukkit.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?]

Caused by: java.lang.NullPointerException

at moe.him188.mymap.utils.Utils.setItemMapToLevel(Utils.java:116) ~[?:?]

at moe.him188.mymap.image.ImageUpdater.updateMapCacheBlock(ImageUpdater.java:122) ~[?:?]

at moe.him188.mymap.image.GIFImageUpdater.updateBlocks(GIFImageUpdater.java:71) ~[?:?]

at moe.him188.mymap.image.GIFImageUpdater.update(GIFImageUpdater.java:48) ~[?:?]

at moe.him188.mymap.MyMapFrame.updateImage0(MyMapFrame.java:178) ~[?:?]

at moe.him188.mymap.MyMapFrame.updateImage(MyMapFrame.java:172) ~[?:?]

at moe.him188.mymap.MyMapFrame.<init>(MyMapFrame.java:67) ~[?:?]

at moe.him188.mymap.MyMapFrame.fromConfigSection(MyMapFrame.java:38) ~[?:?]

at moe.him188.mymap.MyMap.onEnable(MyMap.java:98) ~[?:?]

at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit.jar:?]

at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit.jar:?]

at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[nukkit.jar:?]

... 4 more

**Comment by Him188** [comment]
It seems that you have removed a world in which you set a map. Please delete that config file in /plugin/mymap/images/
