### ISSUE TITLE
Plugin not work

### ISSUE THREAD

**Issue by ghost** [Him188/MyMap#4]
01:05:14 [CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerInteractEvent' to 'MyMap v1.3.0': null on com.him188.mymap.SettingListener
01:05:14 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.level.Level.useItemOn(Level.java:1987)
        at cn.nukkit.level.Level.useItemOn(Level.java:1954)
        at cn.nukkit.Player.handleDataPacket(Player.java:2974)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:188)
        at cn.nukkit.network.Network.processBatch(Network.java:170)
        at cn.nukkit.Player.handleDataPacket(Player.java:2006)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:158)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:67)
        at cn.nukkit.network.Network.processInterfaces(Network.java:78)
        at cn.nukkit.Server.tick(Server.java:1016)
        at cn.nukkit.Server.tickProcessor(Server.java:818)
        at cn.nukkit.Server.start(Server.java:797)
        at cn.nukkit.Server.<init>(Server.java:468)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.NoSuchMethodError: cn.nukkit.network.protocol.ClientboundMapItemDataPacket.encode()V
        at com.him188.mymap.utils.Utils.getClientboundMapItemDataPacket(Utils.java:143)
        at com.him188.mymap.image.StaticImageUpdater.lambda$update$0(StaticImageUpdater.java:44)
        at java.util.HashMap.forEach(Unknown Source)
        at com.him188.mymap.image.StaticImageUpdater.update(StaticImageUpdater.java:40)
        at com.him188.mymap.MyMapFrame.updateImage0(MyMapFrame.java:178)
        at com.him188.mymap.MyMapFrame.updateImage(MyMapFrame.java:172)
        at com.him188.mymap.MyMapFrame.<init>(MyMapFrame.java:67)
        at com.him188.mymap.SettingListener$SettingData.toFrame(SettingListener.java:58)
        at com.him188.mymap.SettingListener$SettingData.access$700(SettingListener.java:32)
        at com.him188.mymap.SettingListener.onInteract(SettingListener.java:125)
        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 18 more

**Comment by Him188** [comment]
Could you find the course? I'm at school this month.

**Comment by Him188** [comment]
which version were your Nukkit working on?

**Comment by ghost** [comment]
https://github.com/NukkitX/Nukkit

Can you update plugin for this version of nukkit?

> java.lang.NullPointerException
        at cn.nukkit.level.Level.getFullBlock(Level.java:1419)
        at cn.nukkit.level.Level.sendBlocks(Level.java:980)
        at cn.nukkit.level.Level.sendBlocks(Level.java:924)
        at cn.nukkit.level.Level.sendBlocks(Level.java:920)
        at com.him188.mymap.image.ImageUpdater.requestBlockUpdate(ImageUpdater.java:156)
        at com.him188.mymap.CommonListener$2.onRun(CommonListener.java:47)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
12:44:14 [CRITICAL] Exception in asynchronous task
java.lang.NullPointerException
        at cn.nukkit.level.Level.getFullBlock(Level.java:1419)
        at cn.nukkit.level.Level.sendBlocks(Level.java:980)
        at cn.nukkit.level.Level.sendBlocks(Level.java:924)
        at cn.nukkit.level.Level.sendBlocks(Level.java:920)
        at com.him188.mymap.image.ImageUpdater.requestBlockUpdate(ImageUpdater.java:156)
        at com.him188.mymap.CommonListener$2.onRun(CommonListener.java:47)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by Him188** [comment]
Have you already updated this plugin? I am now working on it, sorry for my lateness.

**Comment by Him188** [comment]
I have successfully compiled, 
![tim 20180222165323](https://user-images.githubusercontent.com/12100985/36528792-43a180b6-17f1-11e8-8066-dc394dcda1fd.png)
