### ISSUE TITLE
Another bug get corrupted chunks

### ISSUE THREAD

**Issue by ghost** [Him188/MyMap#6]
22:25:29 [INFO] Enabling MyMap v1.3.0
22:25:30 [ALERT] java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(Unknown Source)
        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at cn.nukkit.utils.ZlibThreadLocal.inflate(ZlibThreadLocal.java:85)
        at cn.nukkit.utils.Zlib.inflate(Zlib.java:56)
        at cn.nukkit.utils.Zlib.inflate(Zlib.java:60)
        at cn.nukkit.level.format.anvil.Chunk.fromBinary(Chunk.java:254)
        at cn.nukkit.level.format.anvil.RegionLoader.unserializeChunk(RegionLoader.java:86)
        at cn.nukkit.level.format.anvil.RegionLoader.readChunk(RegionLoader.java:71)
        at cn.nukkit.level.format.anvil.RegionLoader.readChunk(RegionLoader.java:19)
        at cn.nukkit.level.format.anvil.Anvil.loadChunk(Anvil.java:230)
        at cn.nukkit.level.format.generic.BaseLevelProvider.getChunk(BaseLevelProvider.java:372)
        at cn.nukkit.level.Level.forceLoadChunk(Level.java:2606)
        at cn.nukkit.level.Level.getChunk(Level.java:2301)
        at cn.nukkit.level.Level.setBlock(Level.java:1638)
        at cn.nukkit.level.Level.setBlock(Level.java:1631)
        at com.him188.mymap.utils.Utils.setItemMapToLevel(Utils.java:117)
        at com.him188.mymap.image.ImageUpdater.updateMapCacheBlock(ImageUpdater.java:122)
        at com.him188.mymap.image.StaticImageUpdater.lambda$update$0(StaticImageUpdater.java:41)
        at java.util.HashMap.forEach(Unknown Source)
        at com.him188.mymap.image.StaticImageUpdater.update(StaticImageUpdater.java:40)
        at com.him188.mymap.MyMapFrame.updateImage0(MyMapFrame.java:178)
        at com.him188.mymap.MyMapFrame.updateImage(MyMapFrame.java:172)
        at com.him188.mymap.MyMapFrame.<init>(MyMapFrame.java:67)
        at com.him188.mymap.MyMapFrame.fromConfigSection(MyMapFrame.java:38)
        at com.him188.mymap.MyMap.onEnable(MyMap.java:93)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
        at cn.nukkit.Server.enablePlugin(Server.java:660)
        at cn.nukkit.Server.enablePlugins(Server.java:649)
        at cn.nukkit.Server.<init>(Server.java:493)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)

22:25:30 [ERROR] Corrupted chunk detected

**Comment by Him188** [comment]
Is this the result of:

FullChunk chunk = level.getChunk(pos.getFloorX() >> 4, pos.getFloorZ() >> 4, _true_);

but this _true_ had been modified to _false_, i think it will not happen in the future

**Comment by ghost** [comment]
I modified and was happened.

No fix.
