### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Daniel-Ric** [Him188/MyMap#8]
[36m18:32:07[m [[m[34mINFO [m[m] Aktiviere MyMap v1.3.1

[36m18:32:07[m [[m[1;31mERROR[m[m] Throwing

java.lang.RuntimeException: java.lang.NullPointerException

at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [nukkit.jar:?]

at cn.nukkit.Server.enablePlugin(Server.java:733) [nukkit.jar:?]

at cn.nukkit.Server.enablePlugins(Server.java:722) [nukkit.jar:?]

at cn.nukkit.Server.<init>(Server.java:558) [nukkit.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?]

Caused by: java.lang.NullPointerException

at com.him188.mymap.image.StaticImageUpdater.update(StaticImageUpdater.java:39) ~[?:?]

at com.him188.mymap.MyMapFrame.updateImage0(MyMapFrame.java:178) ~[?:?]

at com.him188.mymap.MyMapFrame.updateImage(MyMapFrame.java:172) ~[?:?]

at com.him188.mymap.MyMapFrame.<init>(MyMapFrame.java:67) ~[?:?]

at com.him188.mymap.MyMapFrame.fromConfigSection(MyMapFrame.java:38) ~[?:?]

at com.him188.mymap.MyMap.onEnable(MyMap.java:93) ~[?:?]

at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit.jar:?]

at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit.jar:?]

at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[nukkit.jar:?]

... 4 more

[36m18:32:07[m [[m[34mINFO [m[m] Deaktiviere MyMap v1.3.1

**Comment by Him188** [comment]
Please check your image file(plugins/mymap/images/). The plugin cannot read your image.
